//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Children
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Children()
        {
            this.FutureData = new HashSet<FutureData>();         
        }
    
        public string IdChild { get; set; }
        public string ChildName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string ParentCode { get; set; }
        public byte[] Picture { get; set; }
        public int KinderGardenCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FutureData> FutureData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LiveData> LiveData { get; set; }
        public virtual KinderGarden KinderGarden { get; set; }
        public virtual Users Users { get; set; }
    }
}
