//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    
    public enum Statuses : int
    {
        PRESENT = 1,
        NONPRESENT =2,
        LATE =3,
        ABSENT =4,
        SEND


    }
}
